version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: banco_de_dados # Nome do seu banco de dados
      POSTGRES_USER: usuario # Usuário para o banco de dados
      POSTGRES_PASSWORD: 1234 # Senha para o usuário
    ports:
      - "5432:5432" # Mapeia a porta 5432 do container para a porta 5432 da sua máquina
    volumes:
      - db_data:/var/lib/postgresql/data # Volume para persistir os dados

volumes:
  db_data: