version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: banco_de_dados
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - ./lib/db_data:/var/lib/postgresql/data

  ollama:
    image: ollama/ollama:0.1.34
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ./lib/ollama_data:/var/lib/ollama/.ollama

volumes:
  db_data:
  ollama_data:
